### ISSUE TITLE
A question regarding multiple expectRequire

### ISSUE THREAD

**Issue by cmdelatorre** [alfateam/a#1]
In my test module I _expectRequire_ different modules. Then, at the end of the file, I call ```expectRequire.reset()```

Is that enough? One call to ```reset``` will restore all the mocked modules?

**Comment by lroal** [comment]
Yes. After running expectRequire.reset(), any succeeding calls to require(..) will return the "real" module.
But the module under test (sut)  will be cached by nodejs and still have mocked dependencies - to clean all mocks you need to clear the nodejs cache or run other tests in separate process.

**Comment by lroal** [comment]
How to delete nodejs cache:
```js
Object.keys(require.cache).forEach(function(key) { delete require.cache[key]; });
```

**Comment by cmdelatorre** [comment]
Awesome, thanks for the quick answer.
