### ISSUE TITLE
please add a license :)

### ISSUE THREAD

**Issue by p1tz** [alfateam/a#3]
thank you!

**Comment by nori0990** [comment]
Name

**Comment by nori0990** [comment]
Thread 4 name:  AVAudioSession Notify Thread
Thread 4:
0   libsystem_kernel.dylib        	0x000000018c44b224 0x18c44a000 + 4644
1   libsystem_kernel.dylib        	0x000000018c44b09c 0x18c44a000 + 4252
2   CoreFoundation                	0x000000018d41ce90 0x18d342000 + 896656
3   CoreFoundation                	0x000000018d41aae4 0x18d342000 + 887524
4   CoreFoundation                	0x000000018d34ada4 0x18d342000 + 36260
5   AVFAudio                      	0x00000001a74f2540 0x1a747e000 + 476480
6   AVFAudio                      	0x00000001a7518814 0x1a747e000 + 632852
7   libsystem_pthread.dylib       	0x000000018c53168c 0x18c52e000 + 13964
8   libsystem_pthread.dylib       	0x000000018c53159c 0x18c52e000 + 13724
9   libsystem_pthread.dylib       	0x000000018c52ecb4 0x18c52e000 + 3252

Thread 5 name:  ASDeallocQueue
Thread 5:
